part1: 
	
part2: 

part3: 
	
part4: 

part5: 

part6: 

################## DON'T TOUCH BELOW ##################
run1: part1
	@valgrind ./part1 2> out; python3 val.py 
run2: part2
	@valgrind ./part2 2> out; python3 val.py 
run3: part3
	@valgrind ./part3 2> out; python3 val.py 
run4: part4
	@test -f part4 && echo "part4: Code compiled successfully" 
run5: part5
	@test -f part5 && echo "part5: Code compiled successfully" 
run6: part6
	@test -f part6 && echo "part6: Code compiled successfully" 
